In [98]:
%reload_ext autoreload
%autoreload 2

current_jupyter_path: str = %pwd # type: ignore
while len(current_jupyter_path) > 1 and not current_jupyter_path.endswith("finance-tracker-agent"):
    %cd ..
    current_jupyter_path = %pwd # type: ignore

In [99]:
from langchain.agents import (
    create_tool_calling_agent,
    AgentExecutor,
    create_react_agent,
)
from langchain_openai import ChatOpenAI
from src.tools import (
    save_expense_tool,
    get_current_date_tool,
    get_current_month_tool,
    get_all_expenses,
    update_last_expense_attribute,
    get_spendings_by_year_and_month,
    get_spendings_by_category_for_specific_month,
    get_spendings_by_main_and_subcategory_for_specific_month,
    get_spendings_by_account_for_specific_month,
)
from langchain_core.prompts import ChatPromptTemplate
from langchain import hub
from src.prompts import openai_functions_agent_prompt
from langchain.agents import AgentExecutor, create_openai_functions_agent


llm = ChatOpenAI(model="gpt-3.5-turbo")  # gpt-4.1-mini

In [100]:
prompt = openai_functions_agent_prompt

tools = [
    save_expense_tool,
    get_current_date_tool,
    get_current_month_tool,
    get_all_expenses,
    update_last_expense_attribute,
    get_spendings_by_year_and_month,
    get_spendings_by_category_for_specific_month,
    get_spendings_by_main_and_subcategory_for_specific_month,
    get_spendings_by_account_for_specific_month,
]

agent = create_openai_functions_agent(llm, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

### Get spendings by year and month

In [54]:
input_text = "Based on my expenses in the csv file, can you do a monthly spending report of the last 3 months only? We are in august"
result = agent_executor.invoke({"input": input_text})

print(result["output"])

> Entering new AgentExecutor chain...

Invoking: `get_spendings_by_year_and_month` with `{}`


   date     month  total_spent  average_spent  count
0  2025   January      2101.56      55.304211     38
1  2025  February      1750.00      67.307692     26
2  2025     March      1577.15      47.792424     33
3  2025     April      2195.29      46.708298     47
4  2025       May      1737.72      37.776522     46
5  2025      June      2028.12      41.390204     49
6  2025      July      1820.64      45.516000     40
7  2025    August      1842.17      65.791786     28Here is the monthly spending report for the last 3 months:

- June 2025: Total spent $2028.12, Average spent $41.39, Count 49
- July 2025: Total spent $1820.64, Average spent $45.52, Count 40
- August 2025: Total spent $1842.17, Average spent $65.79, Count 28

> Finished chain.
Here is the monthly spending report for the last 3 months:

- June 2025: Total spent $2028.12, Average spent $41.39, Count 49
- July 2025: Total spent $1820.64, Average spent $45.52, Count 40
- August 2025: Total spent $1842.17, Average spent $65.79, Count 28

### Get spendings by category for specific month

In [69]:
input_text = "Can I get the spendings by category for this current month?"
input_text = "Can I get the spendings by category for the last month?"
# input_text = "Can I get the spendings by category for the month of June?"

result = agent_executor.invoke({"input": input_text})

print(result["output"])

> Entering new AgentExecutor chain...

Invoking: `get_spendings_by_category_for_specific_month` with `{'year': 2025, 'month': 7}`


              main_category  total_spent  average_spent  count
0         AP House Expenses       528.29     176.096667      3
1               Car Expense       203.32      50.830000      4
2   Corroios House Expenses       505.40     168.466667      3
3                    Drinks       106.30      17.716667      6
4                     Fixed        17.18      17.180000      1
5                 Groceries       162.80      23.257143      7
6              Lunch Office        13.00      13.000000      1
7                     Other        58.20       9.700000      6
8                     Phone        23.00      23.000000      1
9          Restaurant Night       141.00      47.000000      3
10                 Variable        62.15      12.430000      5
Invoking: `get_spendings_by_category_for_specific_month` with `{'year': 2025, 'month': 7}`


              main_category  total_spent  average_spent  count
0         AP House Expenses       528.29     176.096667      3
1               Car Expense       203.32      50.830000      4
2   Corroios House Expenses       505.40     168.466667      3
3                    Drinks       106.30      17.716667      6
4                     Fixed        17.18      17.180000      1
5                 Groceries       162.80      23.257143      7
6              Lunch Office        13.00      13.000000      1
7                     Other        58.20       9.700000      6
8                     Phone        23.00      23.000000      1
9          Restaurant Night       141.00      47.000000      3
10                 Variable        62.15      12.430000      5Here are the spendings by category for the last month:

- **AP House Expenses**: Total Spent: $528.29, Average Spent: $176.10, Count: 3
- **Car Expense**: Total Spent: $203.32, Average Spent: $50.83, Count: 4
- **Corroios House Expenses**: Total Spent: $505.40, Average Spent: $168.47, Count: 3
- **Drinks**: Total Spent: $106.30, Average Spent: $17.72, Count: 6
- **Fixed**: Total Spent: $17.18, Average Spent: $17.18, Count: 1
- **Groceries**: Total Spent: $162.80, Average Spent: $23.26, Count: 7
- **Lunch Office**: Total Spent: $13.00, Average Spent: $13.00, Count: 1
- **Other**: Total Spent: $58.20, Average Spent: $9.70, Count: 6
- **Phone**: Total Spent: $23.00, Average Spent: $23.00, Count: 1
- **Restaurant Night**: Total Spent: $141.00, Average Spent: $47.00, Count: 3
- **Variable**: Total Spent: $62.15, Average Spent: $12.43, Count: 5

> Finished chain.
Here are the spendings by category for the last month:

- **AP House Expenses**: Total Spent: $528.29, Average Spent: $176.10, Count: 3
- **Car Expense**: Total Spent: $203.32, Average Spent: $50.83, Count: 4
- **Corroios House Expenses**: Total Spent: $505.40, Average Spent: $168.47, Count: 3
- **Drinks**: Total Spent: $106.30, Average Spent: $17.72, Count: 6
- **Fixed**: Total Spent: $17.18, Average Spent: $17.18, Count: 1
- **Groceries**: Total Spent: $162.80, Average Spent: $23.26, Count: 7
- **Lunch Office**: Total Spent: $13.00, Average Spent: $13.00, Count: 1
- **Other**: Total Spent: $58.20, Average Spent: $9.70, Count: 6
- **Phone**: Total Spent: $23.00, Average Spent: $23.00, Count: 1
- **Restaurant Night**: Total Spent: $141.00, Average Spent: $47.00, Count: 3
- **Variable**: Total Spent: $62.15, Average Spent: $12.43, Count: 5
Here are the spendings by category for the last month:

- **AP House Expenses**: Total Spent: $528.29, Average Spent: $176.10, Count: 3
- **Car Expense**: Total Spent: $203.32, Average Spent: $50.83, Count: 4
- **Corroios House Expenses**: Total Spent: $505.40, Average Spent: $168.47, Count: 3
- **Drinks**: Total Spent: $106.30, Average Spent: $17.72, Count: 6
- **Fixed**: Total Spent: $17.18, Average Spent: $17.18, Count: 1
- **Groceries**: Total Spent: $162.80, Average Spent: $23.26, Count: 7
- **Lunch Office**: Total Spent: $13.00, Average Spent: $13.00, Count: 1
- **Other**: Total Spent: $58.20, Average Spent: $9.70, Count: 6
- **Phone**: Total Spent: $23.00, Average Spent: $23.00, Count: 1
- **Restaurant Night**: Total Spent: $141.00, Average Spent: $47.00, Count: 3
- **Variable**: Total Spent: $62.15, Average Spent: $12.43, Count: 5

> Finished chain.
Here are the spendings by category for the last month:

- **AP House Expenses**: Total Spent: $528.29, Average Spent: $176.10, Count: 3
- **Car Expense**: Total Spent: $203.32, Average Spent: $50.83, Count: 4
- **Corroios House Expenses**: Total Spent: $505.40, Average Spent: $168.47, Count: 3
- **Drinks**: Total Spent: $106.30, Average Spent: $17.72, Count: 6
- **Fixed**: Total Spent: $17.18, Average Spent: $17.18, Count: 1
- **Groceries**: Total Spent: $162.80, Average Spent: $23.26, Count: 7
- **Lunch Office**: Total Spent: $13.00, Average Spent: $13.00, Count: 1
- **Other**: Total Spent: $58.20, Average Spent: $9.70, Count: 6
- **Phone**: Total Spent: $23.00, Average Spent: $23.00, Count: 1
- **Restaurant Night**: Total Spent: $141.00, Average Spent: $47.00, Count: 3
- **Variable**: Total Spent: $62.15, Average Spent: $12.43, Count: 5

### Get spendings by main and sub category for specific month

In [ ]:
input_text = (
    "Can I get the spendings by category and sub_category for this current month?"
)
input_text = "Can I get the spendings by category and sub_category for the last month?"
# input_text = "Can I get the spendings by category and sub_category for the month of June?"

result = agent_executor.invoke({"input": input_text})

print(result["output"])

> Entering new AgentExecutor chain...

Invoking: `get_current_month_tool` with `{}`


2025-08
Invoking: `get_current_month_tool` with `{}`


2025-08
Invoking: `get_spendings_by_main_and_subcategory_for_specific_month` with `{'year': 2025, 'month': 8}`


              main_category            sub_category  total_spent  \
0         AP House Expenses           House Payment       500.00
1               Car Expense              Auto & Gas        60.01
2   Corroios House Expenses                    Rent       450.00
3   Corroios House Expenses                   Water         7.58
4                    Drinks                  Drinks       119.30
5                 Groceries               Groceries       213.58
6                     Other                   Other        71.20
7          Restaurant Night  Restaurant - Enjoyment       167.55
8                  Variable               Apartment        88.00
9                  Variable              Auto & Gas       101.49
10                 Variable                  Coffee        11.85
11                 Variable           Subscriptions        37.61
12                 Variable               Uber Eats        14.00

    average_spent  count
0        500.0000      1
1         30.0050      2
2        450.0000      1
3          7.5800      1
4         23.8600      5
5         42.7160      5
6         35.6000      2
7         41.8875      4
8         88.0000      1
9        101.4900      1
10         5.9250      2
11        18.8050      2
12        14.0000      1
Invoking: `get_spendings_by_main_and_subcategory_for_specific_month` with `{'year': 2025, 'month': 8}`


              main_category            sub_category  total_spent  \
0         AP House Expenses           House Payment       500.00
1               Car Expense              Auto & Gas        60.01
2   Corroios House Expenses                    Rent       450.00
3   Corroios House Expenses                   Water         7.58
4                    Drinks                  Drinks       119.30
5                 Groceries               Groceries       213.58
6                     Other                   Other        71.20
7          Restaurant Night  Restaurant - Enjoyment       167.55
8                  Variable               Apartment        88.00
9                  Variable              Auto & Gas       101.49
10                 Variable                  Coffee        11.85
11                 Variable           Subscriptions        37.61
12                 Variable               Uber Eats        14.00

    average_spent  count
0        500.0000      1
1         30.0050      2
2        450.0000      1
3          7.5800      1
4         23.8600      5
5         42.7160      5
6         35.6000      2
7         41.8875      4
8         88.0000      1
9        101.4900      1
10         5.9250      2
11        18.8050      2
12        14.0000      1  Here are the spendings by category and sub_category for the last month (August 2025):

| main_category         | sub_category            | total_spent | average_spent | count |
|-----------------------|-------------------------|-------------|---------------|-------|
| AP House Expenses     | House Payment           | $500.00     | $500.00       | 1     |
| Car Expense           | Auto & Gas              | $60.01      | $30.00        | 2     |
| Corroios House Expenses| Rent                   | $450.00     | $450.00       | 1     |
| Corroios House Expenses| Water                  | $7.58       | $7.58         | 1     |
| Drinks                | Drinks                  | $119.30     | $23.86        | 5     |
| Groceries             | Groceries               | $213.58     | $42.72        | 5     |
| Other                 | Other                   | $71.20      | $35.60        | 2     |
| Restaurant Night      | Restaurant - Enjoyment  | $167.55     | $41.89        | 4     |
| Variable              | Apartment               | $88.00      | $88.00        | 1     |
| Variable              | Auto & Gas              | $101.49     | $101.49       | 1     |
| Variable              | Coffee                  | $11.85      | $5.93         | 2     |
| Variable              | Subscriptions           | $37.61      | $18.80        | 2     |
| Variable              | Uber Eats               | $14.00      | $14.00        | 1     |

> Finished chain.
Here are the spendings by category and sub_category for the last month (August 2025):

| main_category         | sub_category            | total_spent | average_spent | count |
|-----------------------|-------------------------|-------------|---------------|-------|
| AP House Expenses     | House Payment           | $500.00     | $500.00       | 1     |
| Car Expense           | Auto & Gas              | $60.01      | $30.00        | 2     |
| Corroios House Expenses| Rent                   | $450.00     | $450.00       | 1     |
| Corroios House Expenses| Water                  | $7.58       | $7.58         | 1     |
| Drinks                | Drinks                  | $119.30     | $23.86        | 5     |
| Groceries             | Groceries               | $213.58     | $42.72        | 5     |
| Other                 | Other                   | $71.20      | $35.60        | 2     |
| Restaurant Night      | Restaurant - Enjoyment  | $167.55     | $41.89        | 4     |
| Variable              | Apartment               | $88.00      | $88.00        | 1     |
| Variable              | Auto & Gas              | $101.49     | $101.49       | 1     |
| Variable              | Coffee                  | $11.85      | $5.93         | 2     |
| Variable              | Subscriptions           | $37.61      | $18.80        | 2     |
| Variable              | Uber Eats               | $14.00      | $14.00        | 1     |
Here are the spendings by category and sub_category for the last month (August 2025):

| main_category         | sub_category            | total_spent | average_spent | count |
|-----------------------|-------------------------|-------------|---------------|-------|
| AP House Expenses     | House Payment           | $500.00     | $500.00       | 1     |
| Car Expense           | Auto & Gas              | $60.01      | $30.00        | 2     |
| Corroios House Expenses| Rent                   | $450.00     | $450.00       | 1     |
| Corroios House Expenses| Water                  | $7.58       | $7.58         | 1     |
| Drinks                | Drinks                  | $119.30     | $23.86        | 5     |
| Groceries             | Groceries               | $213.58     | $42.72        | 5     |
| Other                 | Other                   | $71.20      | $35.60        | 2     |
| Restaurant Night      | Restaurant - Enjoyment  | $167.55     | $41.89        | 4     |
| Variable              | Apartment               | $88.00      | $88.00        | 1     |
| Variable              | Auto & Gas              | $101.49     | $101.49       | 1     |
| Variable              | Coffee                  | $11.85      | $5.93         | 2     |
| Variable              | Subscriptions           | $37.61      | $18.80        | 2     |
| Variable              | Uber Eats               | $14.00      | $14.00        | 1     |

> Finished chain.
Here are the spendings by category and sub_category for the last month (August 2025):

| main_category         | sub_category            | total_spent | average_spent | count |
|-----------------------|-------------------------|-------------|---------------|-------|
| AP House Expenses     | House Payment           | $500.00     | $500.00       | 1     |
| Car Expense           | Auto & Gas              | $60.01      | $30.00        | 2     |
| Corroios House Expenses| Rent                   | $450.00     | $450.00       | 1     |
| Corroios House Expenses| Water                  | $7.58       | $7.58         | 1     |
| Drinks                | Drinks                  | $119.30     | $23.86        | 5     |
| Groceries             | Groceries               | $213.58     | $42.72        | 5     |
| Other                 | Other                   | $71.20      | $35.60        | 2     |
| Restaurant Night      | Restaurant - Enjoyment  | $167.55     | $41.89        | 4     |
| Variable              | Apartment               | $88.00      | $88.00        | 1     |
| Variable              | Auto & Gas              | $101.49     | $101.49       | 1     |
| Variable              | Coffee                  | $11.85      | $5.93         | 2     |
| Variable              | Subscriptions           | $37.61      | $18.80        | 2     |
| Variable              | Uber Eats               | $14.00      | $14.00        | 1     |

### Get spendings by account for specific month

In [ ]:
input_text = (
    "Can I get the spendings by category and sub_category for this current month?"
)
input_text = "Can I get the spendings by account?for the last month?"
# input_text = "Can I get the spendings by category and sub_category for the month of June?"

result = agent_executor.invoke({"input": input_text})

print(result["output"])

> Entering new AgentExecutor chain...

Invoking: `get_current_date_tool` with `{}`


2025-08-18
Invoking: `get_current_date_tool` with `{}`


2025-08-18
Invoking: `get_spendings_by_account_for_specific_month` with `{'year': 2025, 'month': 8}`


        account  total_spent  average_spent  count
0  Food Account       159.50      53.166667      3
1  Main Account      1682.67      67.306800     25
Invoking: `get_spendings_by_account_for_specific_month` with `{'year': 2025, 'month': 8}`


        account  total_spent  average_spent  count
0  Food Account       159.50      53.166667      3
1  Main Account      1682.67      67.306800     25### Spendings by Account for Last Month (August 2025):
- **Food Account**:
  - Total Spent: $159.50
  - Average Spent: $53.17
  - Number of Transactions: 3

- **Main Account**:
  - Total Spent: $1682.67
  - Average Spent: $67.31
  - Number of Transactions: 25

> Finished chain.
### Spendings by Account for Last Month (August 2025):
- **Food Account**:
  - Total Spent: $159.50
  - Average Spent: $53.17
  - Number of Transactions: 3

- **Main Account**:
  - Total Spent: $1682.67
  - Average Spent: $67.31
  - Number of Transactions: 25
### Spendings by Account for Last Month (August 2025):
- **Food Account**:
  - Total Spent: $159.50
  - Average Spent: $53.17
  - Number of Transactions: 3

- **Main Account**:
  - Total Spent: $1682.67
  - Average Spent: $67.31
  - Number of Transactions: 25

> Finished chain.
### Spendings by Account for Last Month (August 2025):
- **Food Account**:
  - Total Spent: $159.50
  - Average Spent: $53.17
  - Number of Transactions: 3

- **Main Account**:
  - Total Spent: $1682.67
  - Average Spent: $67.31
  - Number of Transactions: 25

### Get spendings full report

In [101]:
input_text = "Can I get the full and detailed spending report for this current month? Include as much info as possible"

# input_text = "Can I get the spendings by category and sub_category for the month of June?"

result = agent_executor.invoke({"input": input_text})

print(result["output"])

> Entering new AgentExecutor chain...

Invoking: `get_current_month_tool` with `{}`


2025-08
Invoking: `get_spendings_by_main_and_subcategory_for_specific_month` with `{'year': 2025, 'month': 8}`


              main_category            sub_category  total_spent  \
0         AP House Expenses           House Payment       500.00
1               Car Expense              Auto & Gas        60.01
2   Corroios House Expenses                    Rent       450.00
3   Corroios House Expenses                   Water         7.58
4                    Drinks                  Drinks       119.30
5                 Groceries               Groceries       213.58
6                     Other                   Other        71.20
7          Restaurant Night  Restaurant - Enjoyment       167.55
8                  Variable               Apartment        88.00
9                  Variable              Auto & Gas       101.49
10                 Variable                  Coffee        11.85
11                 Variable           Subscriptions        37.61
12                 Variable               Uber Eats        14.00

    average_spent  count
0        500.0000      1
1         30.0050      2
2        450.0000      1
3          7.5800      1
4         23.8600      5
5         42.7160      5
6         35.6000      2
7         41.8875      4
8         88.0000      1
9        101.4900      1
10         5.9250      2
11        18.8050      2
12        14.0000      1  Here is the detailed spending report for the current month (August 2025):

| Main Category          | Sub Category           | Total Spent | Average Spent | Count |
|------------------------|------------------------|-------------|---------------|-------|
| AP House Expenses      | House Payment          | 500.00€     | 500.00€       | 1     |
| Car Expense            | Auto & Gas             | 60.01€      | 30.01€        | 2     |
| Corroios House Expenses| Rent                   | 450.00€     | 450.00€       | 1     |
| Corroios House Expenses| Water                  | 7.58€       | 7.58€         | 1     |
| Drinks                 | Drinks                 | 119.30€     | 23.86€        | 5     |
| Groceries              | Groceries              | 213.58€     | 42.72€        | 5     |
| Other                  | Other                  | 71.20€      | 35.60€        | 2     |
| Restaurant Night       | Restaurant - Enjoyment | 167.55€     | 41.89€        | 4     |
| Variable               | Apartment              | 88.00€      | 88.00€        | 1     |
| Variable               | Auto & Gas             | 101.49€     | 101.49€       | 1     |
| Variable               | Coffee                 | 11.85€      | 5.93€         | 2     |
| Variable               | Subscriptions          | 37.61€      | 18.81€        | 2     |
| Variable               | Uber Eats              | 14.00€      | 14.00€        | 1     |

This report provides a breakdown of expenses by main and sub-categories for the current month.

> Finished chain.
Here is the detailed spending report for the current month (August 2025):

| Main Category          | Sub Category           | Total Spent | Average Spent | Count |
|------------------------|------------------------|-------------|---------------|-------|
| AP House Expenses      | House Payment          | 500.00€     | 500.00€       | 1     |
| Car Expense            | Auto & Gas             | 60.01€      | 30.01€        | 2     |
| Corroios House Expenses| Rent                   | 450.00€     | 450.00€       | 1     |
| Corroios House Expenses| Water                  | 7.58€       | 7.58€         | 1     |
| Drinks                 | Drinks                 | 119.30€     | 23.86€        | 5     |
| Groceries              | Groceries              | 213.58€     | 42.72€        | 5     |
| Other                  | Other                  | 71.20€      | 35.60€        | 2     |
| Restaurant Night       | Restaurant - Enjoyment | 167.55€     | 41.89€        | 4     |
| Variable               | Apartment              | 88.00€      | 88.00€        | 1     |
| Variable               | Auto & Gas             | 101.49€     | 101.49€       | 1     |
| Variable               | Coffee                 | 11.85€      | 5.93€         | 2     |
| Variable               | Subscriptions          | 37.61€      | 18.81€        | 2     |
| Variable               | Uber Eats              | 14.00€      | 14.00€        | 1     |

This report provides a breakdown of expenses by main and sub-categories for the current month.

In [7]:
df.dtypes

year               int64
month             object
main_category     object
sub_category      object
account           object
amount            object
note             float64
dtype: object

In [35]:
df["date"] = pd.to_datetime(df["year"].astype(str) + " " + df["month"], format="%Y %B")

df["month_number"] = df["date"].dt.month

In [42]:
by_year_month_df = (
    df.groupby([df["date"].dt.year, df["month_number"], df["month"]])
    .agg(
        total_spent=pd.NamedAgg(column="amount", aggfunc="sum"),
        average_spent=pd.NamedAgg(column="amount", aggfunc="mean"),
        count=pd.NamedAgg(column="amount", aggfunc="count"),
    )
    .sort_index(level=0)
    .reset_index()
)
by_year_month_df.drop("month_number", inplace=True, axis=1)
by_year_month_df

   date     month  total_spent  average_spent  count
0  2025   January      2101.56      55.304211     38
1  2025  February      1750.00      67.307692     26
2  2025     March      1577.15      47.792424     33
3  2025     April      2195.29      46.708298     47
4  2025       May      1737.72      37.776522     46
5  2025      June      2028.12      41.390204     49
6  2025      July      1820.64      45.516000     40
7  2025    August      1842.17      65.791786     28

In [43]:
by_year_month_df

   date     month  total_spent  average_spent  count
0  2025   January      2101.56      55.304211     38
1  2025  February      1750.00      67.307692     26
2  2025     March      1577.15      47.792424     33
3  2025     April      2195.29      46.708298     47
4  2025       May      1737.72      37.776522     46
5  2025      June      2028.12      41.390204     49
6  2025      July      1820.64      45.516000     40
7  2025    August      1842.17      65.791786     28

In [44]:
by_year_month_df.columns

Index(['date', 'month', 'total_spent', 'average_spent', 'count'], dtype='object')